# Generated by Django 4.1.3 on 2023-02-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_comentario_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='like',
        ),
    ]
